### PR TITLE
CMake Future Proofing Update

### PR DESCRIPTION
**Pull request by bruxisma**
🔨 Add several warning flag checks for clang-11
♻ Refactor generating docs target

This improves what sphinx documentation files look like. While we don't have them currently available anywhere, local tests are being used until the output is satisfactory enough to warrant a 'docs' PR for several C++ projects.

Specifically, this PR makes it so that we can simply do

```cmake
set_property(TARGET ${PROJECT_NAME} PROPERTY SPHINX_GITHUB_USER netlify)
set_property(TARGET ${PROJECT_NAME} PROPERTY SPHINX_GITHUB_REPO ${PROJECT_NAME})
set_property(TARGET ${PROJECT_NAME} PROPERTY SPHINX_COPYRIGHT_OWNER "Netlify, Inc")
```

This makes setting documentation settings a *hell* of a lot easier. Some more work is needed to get us into a 'perfect spot' for setting configuration values and such at configure time, but those can always come later

### CODE REVIEW

**Comment by bruxisma** [comment]
Also of note, is that inside of rst files, we can reference github issues for the active repo if desired. (Reference across to other repos is not yet supported)

Attached is a brief example of what some of the current output looks like
image

**Comment by smoya** [comment]
I have a question regarding the usage of sphinx. Is documentation gonna be autogenerated from some kind of comments or similar? Otherwise, did we decided to go with sphinx output files rather than just use Github README files?

**Comment by bruxisma** [comment]
@smoya Documentation with sphinx + C++ can't be automated at the moment. While there are tools like breathe, or autocppdoc, etc. we use C++20 and those tools generate XML via doxygen that is then converted to rST docs. Thus, we will (unfortunately) have to write our docs by hand, however the intention here is that the docs are both API docs as well as high level docs to explain C++ concepts.

using a GitHub README would put us at a disadvantage especially for API discoverability if just browsing the documentation.

**Comment by bruxisma** [comment]
Some quick notes to add:

[netlify/aegis](https://github.com/netlify/aegis) does not require a change as it does not currently rely on any of the behavior that has changed in this PR.

[netlify/traffic](https://github.com/netlify/traffic) *does* require some changes, however the properties being set there do not affect the current set of targets.

Once documentation files that are in a local branch are added to apex, aegis, and traffic, more care will be needed when making large refactors like this (however, that will most likely not happen until we move to IXM proper)

**Review by fasterthanlime — APPROVED** [review]

**Pull request merged**
